# Generated by Django 3.2.4 on 2021-06-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(0, 'Guest'), (1, 'User'), (2, 'Moderator'), (3, 'Admin')], default=0),
        ),
    ]
